baseURL = "https://chyroc.cn"
languageCode = "zh-cn"
title = "Chyroc的博客"
theme = "xmin"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "友链"
    url = "/blogroll/"
    weight = 2
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3

[params]
    footer = "&copy; [Chyroc](https://chyroc.cn) [Theme By xmin](https://xmin.yihui.name/) 2018"